Repository klaasnicolaas/home-assistant-glow, pull requests merged in 2021-11, with the labels that each got.

#81 Change master to main branch
  .github/workflows/labels.yaml
  .github/workflows/release-drafter.yaml
Labels: enhancement, ci

#86 update to ESPHome 2021.11
  home_assistant_glow.yaml
Labels: new-feature

#89 #88 Fix entity_category by removing extra tags
  home_assistant_glow.yaml
Labels: enhancement
