Repository klaasnicolaas/home-assistant-glow, pull requests merged in 2024-06, with the labels that each got.

#493 Update OTA configuration for ESPHome 2024.6.0
  .github/workflows/build-firmware.yaml
  home-assistant-glow/d1_mini.yaml
  home-assistant-glow/esp32.yaml
  home-assistant-glow/esp8266.yaml
Labels: enhancement

#496 Update build workflow
  .github/workflows/build-firmware.yaml
Labels: maintenance

#497 Add release url to manifest
  .github/workflows/build-firmware.yaml
Labels: maintenance

#502 Use new action for PR labels validation
  .github/workflows/pr-labels.yaml
Labels: ci

#505 Add support for OTA via http_requests
  home-assistant-glow/d1_mini.yaml
  home-assistant-glow/esp32.yaml
  home-assistant-glow/esp8266.yaml
Labels: new-feature

#507 Add ota ids to allow local overriding
  components/updates.yaml
Labels: enhancement

#510 Refactor the build & deploy github actions
  .github/release-drafter.yml
  .github/workflows/build-firmware.yaml
  .github/workflows/deploy-firmware.yaml
Labels: ci

#511 Prevent deploying if branch != main
  .github/workflows/deploy-firmware.yaml
  home-assistant-glow/d1_mini.yaml
  home-assistant-glow/esp32.yaml
  home-assistant-glow/esp8266.yaml
Labels: maintenance, ci
