Repository klaasnicolaas/home-assistant-glow, pull requests merged in 2024-01, with the labels that each got.

#320 🎆Updates maintenance/license year to 2024
  LICENSE
  Readme.md
Labels: maintenance

#322 Update hardware list urls
  Readme.md
Labels: documentation

#327 First batch of changes for new docs website
  .github/workflows/build-firmware.yaml
  docs/docusaurus.config.ts
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/css/custom.css
  docs/src/pages/index.tsx
  docs/static/img/glowing-star.svg
  docs/static/img/undraw_docusaurus_mountain.svg
  docs/static/img/undraw_docusaurus_react.svg
  docs/static/img/undraw_docusaurus_tree.svg
  docs/static/img/undraw_metrics.svg
  docs/static/img/undraw_setup_wizard.svg
  docs/static/img/undraw_showing_support.svg
Labels: documentation

#328 Revert "Bump actions/download-artifact from 3 to 4"
  .github/workflows/build-firmware.yaml
Labels: ci

#329 Revert "Bump actions/upload-artifact from 3 to 4"
  .github/workflows/build-firmware.yaml
Labels: ci

#333 Completion of information on docs website
  .github/workflows/build-firmware.yaml
  Readme.md
  docs/blog/2019-05-28-first-blog-post.md
  docs/blog/2019-05-29-long-blog-post.md
  docs/blog/2021-08-01-mdx-blog-post.mdx
  docs/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg
  docs/blog/2021-08-26-welcome/index.md
  docs/blog/authors.yml
  docs/docs/advanced/firmware_customization.mdx
  docs/docs/configuration.mdx
  docs/docs/faq/faq_nr1.mdx
  docs/docs/faq/faq_nr2.md
  docs/docs/faq/faq_nr3.md
  docs/docs/faq/faq_nr4.md
  docs/docs/getting-started.mdx
  docs/docs/introduction.md
  docs/docs/introduction.mdx
  docs/docs/reference/cases.mdx
  docs/docs/reference/diagram.mdx
  docs/docs/tutorial-basics/_category_.json
  docs/docs/tutorial-basics/congratulations.md
  docs/docs/tutorial-basics/create-a-blog-post.md
  docs/docs/tutorial-basics/create-a-document.md
  docs/docs/tutorial-basics/create-a-page.md
  docs/docs/tutorial-basics/deploy-your-site.md
  docs/docs/tutorial-basics/markdown-features.mdx
  docs/docs/tutorial-extras/_category_.json
  docs/docs/tutorial-extras/img/docsVersionDropdown.png
  docs/docs/tutorial-extras/img/localeDropdown.png
  docs/docs/tutorial-extras/manage-docs-versions.md
  docs/docs/tutorial-extras/translate-your-site.md
  docs/docusaurus.config.ts
  docs/package-lock.json
  docs/package.json
  docs/sidebars.ts
  docs/src/css/custom.css
  docs/src/pages/markdown-page.md
  docs/src/theme/MDXComponents.js
  docs/static/cases/ESP32S/ESP32_bottom_side_v1.stl
  docs/static/cases/ESP32S/ESP32_top_side_v1.stl
  docs/static/cases/ESP32S/esp32s_case.jpg
  docs/static/cases/Home_Assistant_Glow.step
  docs/static/cases/Photodiode_PCB/Sensor_bottom_side_v1.stl
  docs/static/cases/Photodiode_PCB/Sensor_top_side_v1.stl
  docs/static/cases/Photodiode_PCB/sensor_case.jpg
  docs/static/img/configuration/rename-device.png
  docs/static/img/customization/adopt.png
  docs/static/img/faq/correct_board.png
  docs/static/img/home-assistant-glow.jpg
  docs/static/img/installation/auto-discovery.png
  docs/static/img/installation/my-link.png
  docs/static/img/installation/pulse_rate-webserver.png
  docs/static/img/pulse_rate.png
  docs/static/img/wiring_diagram.png
Labels: documentation

#334 Add local search to documentation site
  docs/docusaurus.config.ts
  docs/package-lock.json
  docs/package.json
  docs/static/img/favicon.ico
Labels: documentation

#335 Change default pulse pin for ESP32 to GPIO26
  docs/docs/reference/diagram.mdx
  home-assistant-glow/esp32.yaml
Labels: documentation, breaking-change

#336 Add mac_suffix to device name
  home-assistant-glow/d1_mini.yaml
  home-assistant-glow/esp32.yaml
  home-assistant-glow/esp8266.yaml
Labels: enhancement

#337 Add blog about the changes
  docs/blog/2024-01-11-fresh-new-start.md
Labels: documentation

#338 Move to renovate bot for dependency updates
  .github/dependabot.yml
  .github/renovate.json
Labels: maintenance

#356 Improve the build workflow
  .github/workflows/build-firmware.yaml
Labels: maintenance

#357 Make small changes on the documentation
  docs/blog/2024-01-11-fresh-new-start.md
  docs/docs/introduction.mdx
  docs/docusaurus.config.ts
  docs/src/pages/index.tsx
Labels: documentation

#360 Try to fix manifest file error
  docs/src/components/EspInstallButton.tsx
Labels: bugfix

#359 Add FAQ item about installation process
  docs/docs/faq/faq_nr1.md
  docs/docs/faq/faq_nr5.md
  docs/docs/faq/faq_nr6.md
  docs/docs/faq/img/correct_board.png
  docs/docs/faq/img/failed_manifest.png
  docs/docs/faq/img/spinning_connecting.png
Labels: documentation

#362 Update board configuration for ESP32 and ESP8266
  home-assistant-glow/esp32.yaml
  home-assistant-glow/esp8266.yaml
Labels: enhancement

#372 Add Google Analytics
  docs/docusaurus.config.ts
Labels: documentation

#374 BUG fix: Added properly top case to the cases' folder
  docs/static/cases/ESP32-WROOM-32D/ESP32-WROOM-32D_top_case.stl
Labels: bugfix

#375 Remove because is is also the default setting
  home-assistant-glow/d1_mini.yaml
  home-assistant-glow/esp32.yaml
  home-assistant-glow/esp8266.yaml
Labels: enhancement

#376 Fix issues in github actions
  .github/workflows/build-firmware.yaml
  .github/workflows/labels.yaml
  .github/workflows/release-drafter.yaml
  docs/docs/advanced/firmware_customization.mdx
  docs/src/pages/index.tsx
Labels: documentation, ci

#377 Add github as icon in the navbar
  docs/docusaurus.config.ts
  docs/src/css/custom.css
  docs/src/css/navbar.css
  docs/static/img/brand-github-inverted.svg
  docs/static/img/brand-github.svg
Labels: documentation
